In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
dirname = "sotsuken/"
os.makedirs(dirname, exist_ok=True)
%matplotlib inline
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (11, 5)  #set default figure size
import numpy as np
import scipy.linalg as la

import quantecon as qe
# ずっと使ってきたやつ
set_parameter = 3

# ch10
# set_parameter = 2
# 効用関数の設定
# LQR_util = 2で効用をマイナスに設定
# LQR_util = 2ではLQRの重み行列が正定値行列とならず破綻
LQR_util = 1
if set_parameter == 1:
    # Set parameters ずっと使ってきたやつ
    mu_d = 13.0
    rho = 0.05
    gan = 8.0
    c_d = 1.0
    beta_std = 0.95
    R_kinri = 1 / beta_std
    ponji = 1e-9
elif set_parameter == 2:
    # Set parameters in ch10
    mu_d = 13.594
    rho = 0.241
    gan = 500.0
    c_d = 0.2
    beta_std = 0.997
    R_kinri = 1 / beta_std
    ponji = 1e-9
elif set_parameter == 3:
    # 自由に変えていいよ
    mu_d = 13.00
    rho = 0.6
    gan = 8.
    c_d = 1.0
    #beta_std = 0.9494764430324878
    beta_std = 0.9999
    R_kinri = 1 / beta_std
    ponji = 1e-2
sig_arr = [-1e-12, -1e-1]
d_first = 0.0
k_first = 0.0
# uncertaintyあり、なし全ての期間を決定
iter_t = 1500
iter_uti= iter_t
np.random.seed(7)
eps = np.random.randn(iter_t)
ovr = 50
tapple_y = 20
y_lim = (-ovr, ovr)
# おまじない
%load_ext autoreload
%autoreload 2
# olrprobust_3はリカッチのif文を削除した
# olrprobust_2との相違点は上記があるか、ないか
from olrprobust_3_using import olrp, olrprobust, doubleo

# olrprobust_2はリカッチのif文有〼
# matlabを極力そのまま移し替えた。
# from olrprobust_2_using import olrp, olrprobust, doubleo

# olrprobust_1はgithubから
# from olrprobust_1_using import olrp,olrprobust,doubleo
# y=[d k]のやつ
QLQ_mat = np.array([[0.0, 0.0], [0.0, ponji]])
ALQ_mat = np.array(
    [[rho, 0.0], [1.0, R_kinri]]
)
# u=\gamma - c_tにしたため符号を反転した
BLQ_mat = np.array([[0.0], [1.0]])
CLQ_mat = np.array([ [c_d], [0.0]])
RLQ_mat = np.array([[1]])

if LQR_util == 2:
    RLQ_mat = -RLQ_mat
    QLQ_mat = -QLQ_mat
F_nomis_mat, K_nomis_mat, P_nomis_mat, Pt_nomis_mat = olrprobust(
    beta_std, ALQ_mat, BLQ_mat, CLQ_mat, QLQ_mat, RLQ_mat, sig_arr[0]
)


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
sdfgsdfg
sdfgsdfg


In [4]:
BtLQ_mat=np.hstack([BLQ_mat,CLQ_mat])
print(BtLQ_mat)

[[0. 1.]
 [1. 0.]]


In [5]:
Co=np.hstack([BtLQ_mat,ALQ_mat*BtLQ_mat,ALQ_mat**2*BtLQ_mat])
print(Co)

[[0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0.]]


In [6]:
np.linalg.matrix_rank(Co)

2