%function [f,p] = olrp(beta,A,B,Q,R,W)  
%%OLRP can have arguments: (beta,A,B,Q,R) if there are no cross products  
%     (i.e. W=0).  Set beta=1, if there is no discounting.  
%   
%     OLRP calculates f of the feedback law:  
%                 
%		u = -fx  
%    
%  that maximizes the function:  
%  
%          sum {beta^t [x'Qx + u'Ru +2x'Wu] }  
%    
%  subject to   
%		x[t+1] = Ax[t] + Bu[t]   
%  
%  where x is the nx1 vector of states, u is the kx1 vector of controls,  
%  A is nxn, B is nxk, Q is nxn, R is kxk, W is nxk.  
%                  
%    Also returned is p, the steady-state solution to the associated   
%  discrete matrix Riccati equation.  
%


orlpは最適線形規制問題（Optimal Linear Regulation Problem）の略


In [93]:
import numpy as np
from numpy import dot, eye
from math import sqrt
from killergraphfuncs import olrp,doubleo

SciPyのlinalg（線形代数）モジュールから、逆行列を計算するinv関数、連立一次方程式を解くsolve関数、固有値を計算するeig関数をインポート

In [94]:
from scipy.linalg import inv,solve,eig

In [95]:
def olrp(beta, A, B, Q, R, W=None, tol=1e-6, max_iter=1000):
    return 

適当に行列を指定

In [96]:
A, B, Q, R = np.zeros((4, 4, 3))
W = None
beta = 0
max_iter = 1000
tol = 1e-6

# ここから書き換え開始

行列Aの形状（つまり行数と列数）の最大値を取得

In [97]:
m = max(A.shape)


In [98]:
print(m)
print(A)
Ac,Ab = A.shape
print(Ab)
#このように指定すると行数、列数を取り出せる。

4
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3


from matlab,[rb,cb]=size(B);  
これは行列Bの行数、列数を抜き出している

In [99]:
rc, cb = B.shape

from matlab,  
if nargin==5; W=zeros(m,cb); end;  
これは引数の数が5個である、すなわちW=Noneの時、Wにm×cbの0行列を代入することを書いている

In [100]:

if W is None:
    W = np.zeros((m, cb))


In [101]:
print(W)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


from matlab,  
if min(abs(eig(R)))>1e-5;  
Rの固有値を計算し、その絶対値の最小値が閾値以上ならという意味

In [102]:
if np.min(np.abs(eig(R))) > 1e-5:
    A = sqrt(beta) * (A - B.dot(solve(R, W.T)))
    B = sqrt(beta) * B
    Q = Q - W.dot(solve(R, W.T))
    # k, s are different than in the matlab
    k, s = doubleo(A.T, B.T, Q, R)

    f = k.T + solve(R, W.T)

    p = s

else:
    p0 = -0.1 * np.eye(m)
    dd = 1
    it = 1

    for it in range(max_iter):
        f0 = solve(R + beta * B.T.dot(p0).dot(B),
                    beta * B.T.dot(p0).dot(A) + W.T)
        p1 = beta * A.T.dot(p0).dot(A) + Q - \
            (beta * A.T.dot(p0).dot(B) + W).dot(f0)
        f1 = solve(R + beta * B.T.dot(p1).dot(B),
                    beta * B.T.dot(p1).dot(A) + W.T)
        dd = np.max(f1 - f0)
        p0 = p1

        if dd > tol:
            break
    else:
        msg = 'No convergence: Iteration limit of {0} reached in OLRP'
        raise ValueError(msg.format(max_iter))

    f = f1
    p = p1

#return f, p

ValueError: expected square matrix